'use strict';

const express = require('express');
const { calculateTotal } = require('../lib/emissionEngine');
const { generateInsights } = require('../lib/recommendationEngine');
const { validateFootprintInput, isValidAnonymousId } = require('../lib/validate');
const { addEntry, getEntries } = require('../lib/historyStore');
const factors = require('../data/factors.json');

const router = express.Router();

router.get('/benchmarks', (_req, res) => {
  res.json({ benchmarks: factors.benchmarks });
});

router.post('/calculate', (req, res) => {
  const { valid, errors } = validateFootprintInput(req.body);
  if (!valid) return res.status(400).json({ error: 'Invalid input', details: errors });

  const result = calculateTotal(req.body);
  res.json(result);
});

router.post('/insights', (req, res) => {
  const { valid, errors } = validateFootprintInput(req.body);
  if (!valid) return res.status(400).json({ error: 'Invalid input', details: errors });

  const insights = generateInsights(req.body);
  res.json(insights);
});

router.post('/track', (req, res) => {
  const { anonymousId, totals } = req.body || {};

  if (!isValidAnonymousId(anonymousId)) {
    return res.status(400).json({ error: 'anonymousId must be a valid UUID v4 generated by the client.' });
  }
  if (!totals || typeof totals.totalTonnesPerYear !== 'number') {
    return res.status(400).json({ error: 'totals.totalTonnesPerYear (number) is required.' });
  }

  const entries = addEntry(anonymousId, {
    totalTonnesPerYear: totals.totalTonnesPerYear,
    breakdown: totals.breakdown || null
  });

  res.status(201).json({ entriesStored: entries.length });
});

router.get('/track/:anonymousId', (req, res) => {
  if (!isValidAnonymousId(req.params.anonymousId)) {
    return res.status(400).json({ error: 'anonymousId must be a valid UUID v4.' });
  }
  res.json({ entries: getEntries(req.params.anonymousId) });
});

module.exports = router;
